### ISSUE TITLE
Unable to start when installed to MINGW64 installation on Windows

### ISSUE THREAD

**Issue by prculley** [corb555/GeoFinder#4]
**Describe the bug**
The install via pip3 claimed success.
When I tried to start by using "geofinder" on the command line, I got a quick popup with "Fatal Error in Launcher" "Unable to create process using '*'"

**To Reproduce**
1. type "geofinder" at command prompt or double-click geofinder.exe in the 'bin' directory of my MSYS2/MINGW64 installation.
2. See error for a couple of seconds, then it disappears.

**Desktop (please complete the following information):**
 - OS: WIN10

**Additional context**
I also tried starting with "python3 geofinder.py" from the site-packages directory.  This at least brought up a gui, although it dumped messages on the command terminal.

I then pressed the 'Quit' button before doing anything else and it did not quit; I had to use the 'x' in the corner to end it.  The following was on the console:
C:\msys64\mingw64\lib\python3.6\site-packages\geofinder>python3 geofinder.py
GeoFinder v0.7.4
Python 3.6
GeoFinder Requires Python 3.6 or higher
INFO __main__.setup_logging 715: geofinder Init
DEBUG __main__.check_configuration 807: load country selections list
DEBUG geofinder.CachedDictionary.read 52: Read success CachedDict dir=C:\Users\prc\geoname_data\cache fname=country_list.pkl len=0
WARNING __main__.check_configuration 812: no countries specified
INFO __main__.check_configuration 818: Found C:\Users\prc\geoname_data\cache\geodata.db
DEBUG geofinder.Config.read 55: config read C:\Users\prc\geoname_data\cache config.pkl
DEBUG geofinder.CachedDictionary.read 52: Read success CachedDict dir=C:\Users\prc\geoname_data\cache fname=config.pkl len=1
DEBUG geofinder.CachedDictionary.write 68: Write C:\Users\prc\geoname_data\cache\config.pkl
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\msys64\mingw64\lib\python3.6\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "geofinder.py", line 748, in shutdown
    self.out_diag_file.close()
AttributeError: 'GeoFinder' object has no attribute 'out_diag_file'

**Comment by corb555** [comment]
Thanks for the detailed description.  The last item is fixed in the latest version - shutting down not functioning when there is no database.  Other than that, the diagnostics in the command terminal all look normal.  Since this is a new release I have verbose debugging output to the console, which you can ignore.  If you upgrade to latest version and launch as you described in the last part - geofinder should function correctly.  To upgrade:

`pip3 install geofinder --upgrade`

I'm not sure what is causing the launch failure when you just type geofinder.

**Comment by prculley** [comment]
I think the original issue is due to some problem with pip on Windows machines.  There are reports of this issue by others.  I will see if I can figure it out...

**Comment by prculley** [comment]
I upgrade pip versions on my system pip is now at 19.3.1.  This changed the error to
"Fatal Error in Launcher" "Unable to create process using 'C:\msys64\mingw64\bin\pythonw3.exe C:\msys64\mingw64\lib\python3.6\site-packages\geofinder\gofinder.py'"

It took me a while to notice that the version of the python executable is "pythonw3.exe", which did not exist on my system.  I do have a "python3w.exe" on my system.

It looks like adding 'w' to the "python3" is supposed to avoid a console window; what I don't know if this is standard with the setuptools, or something under your control.

In any event, the program starts if I create a copy of python3w.exe and name it pythonw3.exe.

**Comment by corb555** [comment]
geofinder uses standard utilities, setuptools and pip, to do the install.  Setup.py is used to launch setuptools.  Setup.py includes the configuration information for setuptools.  I specify:
entry_points={
        'gui_scripts'

This tells the system to launch geofinder as a GUI rather than as a console script.   I don't know how that ends up utilizing python3w or pythonw3.  On my Mac, the config has no effect and the console is still launched.  There is no python3w or pythonw3.   I'll check later to see what I have on my Windows7 system.  I can remove the gui_scripts parameter, in which case Geofinder will be launched from a console window.  The upside and downside to that there will be an open console window in addition to geofinder and all the logger printouts will be visible.

setuptools docs are here:
https://setuptools.readthedocs.io/en/latest/setuptools.html

**Comment by corb555** [comment]
I just published 0.8.8.  This changes geofinder setup.py config from gui_script to console_script.  It should now bring up a console window and launch geofinder from there rather than launching without console window.
